### ISSUE TITLE
Can't resolve './Basic'

### ISSUE THREAD

**Issue by abdullah-ihc** [devilwjp/veaury#30]
In react app it always give error 
 Can't resolve './Basic' in '{path}\src\components\Context'
so Basic.vue is vue file.

Steps I am performing

- create-react-app
- npm run eject
- update webpack.config.js
- npm install vue (vue 3.*.*)
- npm install veaury

what is the wrong I am doing?

My Basic.vue file is
```
<template>
  <div class="vue-component">
    <h3>This is the Vue Component.</h3>
    <slot/>
  </div>
</template>
<script>
export default {

}
</script>
<style scoped>

</style>
```

My index.js file under component is 

```
import {applyVueInReact} from 'veaury'
import BasicVue from './Basic'
import {useEffect, useState, useRef, createContext, useContext} from 'react'

const Basic = applyVueInReact(BasicVue)
const Context = createContext({})

function SubReactComponent() {
  const {bossName} = useContext(Context)
  return <div className="slot">bossName from Context: {bossName}</div>
}

export default function () {
  const [bossName, setBossName] = useState(Math.random)
  const timer = useRef(null)
  useEffect(() => {
    timer.current = setInterval(() => {
      setBossName(Math.random())
    }, 1000)
    return () => {
      clearInterval(timer.current)
    }
  }, [])
  return <div>
    <h3>This example shows the basic usage of `applyVueInReact`.</h3>
    <h4>Using React components in Vue components.</h4>
    <Context.Provider value={{bossName}}>
      <Basic>
        <div className="slot">
          This is the Vue component Slot from React<br/>
          <SubReactComponent/>
        </div>
      </Basic>
    </Context.Provider>
  </div>
}
```

**Comment by devilwjp** [comment]
@abdullah-ihc 
You can refer to [How to configure Vue in the React project from 'create-react-app'](https://github.com/devilwjp/veaury/tree/master/dev-project-react)  
The main reason is that your React project doesn't recognize files with `.vue` suffix.  
I think the problem is caused by not using `veaury/webpack/VeauryVuePlugin`.

**Comment by devilwjp** [comment]
@abdullah-ihc 
Sorry, I realize your problem is that the `vue` file type is not added to resolve.extensions in the webpack configuration, if your project was created with `create-react-app` and you run `npm run eject` `, then you can add the `vue` file type to `config/webpack/paths.js`.

![image](https://user-images.githubusercontent.com/38802722/184545927-e2a1c06e-43a7-48e5-bd7f-6888169994ea.png)

**Comment by devilwjp** [comment]
@abdullah-ihc 
After updating to `veaury@2.2.8`, `veaury/webpack/VeauryVuePlugin` will add the `vue` file type by default, no longer need to configure manually

**Comment by abdullah-ihc** [comment]
Thanks, @devilwjp for the updated version. It is working now :)
