### ISSUE TITLE
React router dom.

### ISSUE THREAD

**Issue by 402Martin** [devilwjp/veaury#4]
Hi, does veaury on vue allow the react components work with react-router dom

**Comment by devilwjp** [comment]
@402Martin 
If the base project is vue, vue-router should be used, otherwise there will be conflict scenarios where vue-router and react-router interact with each other.  


When the react component is imported into the vue project through veaury, it is recommended to use vue-router through `injectPropsFromWrapper` in the react components.

**Comment by devilwjp** [comment]
@402Martin 
I tried to use vue-router and react-router at the same time, and it runs smoothly, you can refer to `dev-project-react/src/components/reactMissVue`
