### ISSUE TITLE
React in Vue: Uncaught Error: Objects are not valid as a React child

### ISSUE THREAD

**Issue by tyrell-barbri** [devilwjp/veaury#41]
I'm trying to get a React component to work in a Vue project, but the component doesn't show and I keep seeing this error in the console.

![error](https://user-images.githubusercontent.com/89483831/197061458-73a272db-c8ed-4f9a-b243-f0e2d2e2b95c.PNG)

The React component is just an h1 with 'Hi, I'm a React component'. This is a new Vue project made with @vue/cli.

App.vue
![app](https://user-images.githubusercontent.com/89483831/197061697-157f14f8-d662-43ec-b8c8-464356be3224.PNG)

babel.config.js
![babel](https://user-images.githubusercontent.com/89483831/197061786-201e07f8-e97f-4382-b361-f17d397c0956.PNG)

package.json
![package](https://user-images.githubusercontent.com/89483831/197061820-503fd9a1-42ca-4ff0-a767-062f8feb903a.PNG)

**Comment by devilwjp** [comment]
@tyrell-barbri 
![image](https://user-images.githubusercontent.com/38802722/197093543-fb65fdb4-eb6d-4d5b-8ad7-b9a4a9e2c4f7.png)
Because the options of your veauryPreset only set the js or jsx files in the abc directory to be compiled into react jsx, and your react component is in the react_app directory, remove the custom option settings (defaut is react_app), it works fine.

**Comment by tyrell-barbri** [comment]
It's working now. Thanks!

**Comment by YogiWu** [comment]
i meet this problem too. i use vite and the version of pacakges is vite 4.3.5, vue 3.3.1 react 18.2.0
