### ISSUE TITLE
Vue 3.3 support

### ISSUE THREAD

**Issue by anhcuong203** [devilwjp/veaury#81]
Hi. I want to use Vue 3.3 and React at the same time. How could I modify Vue 3.3 to do that? File runtime-dom.d.ts had changed.
Many thanks!

**Comment by devilwjp** [comment]
@anhcuong203 
Veaury supports vue3.3, but if you need to use TS, you should modify the TS signature file, otherwise it will cause type judgment conflicts.

Regarding the modification of the TS signature file, each version is different, so you need to modify it yourself. There is a case of modifying the TS signature file in my document, you can refer to it

**Comment by devilwjp** [comment]
@anhcuong203 
Or you can provide the git address of your project, I will fork it, and try to help you modify the signature file.
